name: StudyRats CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job 1: Testar o Backend (Laravel)
  laravel-backend:
    runs-on: ubuntu-latest
    
    # Sobe um banco de dados temporário para os testes
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: studyrats_test
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, dom, curl, libxml, postgres

    - name: Install Backend Dependencies
      run: composer install --prefer-dist --no-progress
      working-directory: ./api

    - name: Run Migrations and Tests
      run: |
        cp .env.example .env.testing
        php artisan test
      working-directory: ./api
      env:
        DB_CONNECTION: pgsql
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_DATABASE: studyrats_test
        DB_USERNAME: postgres
        DB_PASSWORD: password

  # Job 2: Validar o Frontend (React Native)
  mobile-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Frontend Dependencies
      run: npm install
      working-directory: ./mobile

    - name: Run Lint (Verificação de erros de escrita)
      run: npm run lint --if-present
      working-directory: ./mobile